### ISSUE TITLE
Question about changing the cache path in AppKernal

### ISSUE THREAD

**Issue by dominickp** [kleiram/vagrant-symfony#22]
Hey, 
What is the best method for keeping the update cache paths only in the development environment and not in production? I believe AppKernal is part of my git repo and I think ignoring it would cause more problems than it solves.

**Comment by kleiram** [comment]
Ah, what you can do is:

```php
public function getCacheDir()
{
    if (in_array($this->environment, ['dev', 'test'])) {
        return '/tmp/symfony/cache/'. $this->environment;
    }

    return parent::getCacheDir();
}
```

Hope that helps!

**Comment by dominickp** [comment]
Thanks man!

**Comment by kleiram** [comment]
You're welcome! Enjoy!
