### ISSUE TITLE
Won't install on Windows

### ISSUE THREAD

**Issue by numediaweb** [kleiram/vagrant-symfony#26]
I tried to vagrant up on windows 10 but I got lots of errors, the last one was:
```
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.
```
I installed Cygwin (and all the dependency modules) and now when I run `which ansible-playbook` I get `/usr/bin/ansible-playbook`.

Also when I run `which Vagrant` I get `/cygdrive/c/HashiCorp/Vagrant/bin/Vagrant`.

So I guss I have everything installed but still I get this error.

**Comment by kleiram** [comment]
This is weird...what is in your `PATH`? Not really sure how to display it in Windows, but maybe the following command can tell more (in Cygwin):

```shell
$ echo $PATH
```

**Comment by numediaweb** [comment]
this is the content of my patch:
```
/usr/local/bin:/usr/bin:/home/aidrissi/.local/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/HashiCorp/Vagrant/bin:/cygdrive/c/wamp/bin/php/php5.5.12:/cygdrive/d/tools/modman-php:/cygdrive/c/ProgramData/ComposerSetup/bin:/cygdrive/d/tools/apache-ant-1.9.6/bin:/cygdrive/c/Ruby22-x64/bin:/cygdrive/c/Users/aidrissi/AppData/Roaming/npm:/cygdrive/c/Program Files (x86)/GnuWin32/bin:/cygdrive/d/tools/symfony:/cygdrive/d/tools/babun/.babun:/cygdrive/c/wamp/bin/mysql/mysql5.6.17/bin:/cygdrive/d/tools/.babun
```

I guess I don't have Ansible installed as it is not supported in Windows (or at least I couldn't figure out a way to install it)

**Comment by kleiram** [comment]
Ah, that's a pity! I guess Windows host machines are not supported indeed...that's really a bummer!

I'm afraid there's not a lot I can do to help you...perhaps there are other configurations out there using Puppet or Chef. I'll look around! For now, I'm going to close this issue.
