### ISSUE TITLE
Set the "date.timezone" setting in php.ini

### ISSUE THREAD

**Issue by miguelplazasr** [kleiram/vagrant-symfony#27]
Hi, i try to update the date.timezone in php.ini but does not work. 
I change the file in "/etc/php5/fpm/php.ini". 

Another thing is, how to install the intl extension ??
Thanks

**Comment by w2pc** [comment]
You should be overriding any setting in your configuration not directly in
php.ini

**Comment by kleiram** [comment]
@w2pc is correct, but, if you really want to change your `php.ini` (which will be overwritten when running `vagrant reload`), you have to change both `fpm/php.ini` _and_ `cli/php.ini`.

Installing the `intl` extension is easy, just run the following:

```shell
$ sudo apt-get install php5-intl
```

Hope this helps!
