### ISSUE TITLE
PHPUnit does not pass any test

### ISSUE THREAD

**Issue by merdes** [kleiram/vagrant-symfony#33]
Hello,

I'm using this vagrant box, but since i'm using PHPUnit out of the box the the tests are not passing, i get errors in all the tests.

Anyone with the same problem?

**Comment by mablae** [comment]
@merdes At least post the error you get, this is nothing.

**Comment by merdes** [comment]
@mablae I solved this adding phpunit to my composer as a dev dependency. I don't had any simple error, it was basically all test failing.
